---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 战66.
--- DateTime: 2025/3/4 14:22
---

-- 1.参数列表
-- 1.1优惠券id
local voucherId = ARGV[1]
-- 1.2用户id
local userId = ARGV[2]

-- 2.拼接key
-- 2.1 库存，用于库存剩余判断
local stockKey = "seckill:stock:" .. voucherId
-- 2.2 特定优惠券的购买人群，用于一人一单判断
local orderKey = "seckill:order:" .. voucherId

-- 3.判断库存
if (tonumber(redis.call('get', stockKey)) <= 0) then
    -- 库存不足
    return 1
end

-- 4.判断一人一单
if (redis.call('sismember', orderKey, userId) == 1) then
    -- 用户之前已购买过
    return 2
end

-- 5.具备购买条件
-- 5.1购买后减库存
redis.call('incrby', stockKey, -1)
-- 5.2保存下单用户
redis.call('sadd', orderKey, userId)
return 0